# Generated by Django 6.0.3 on 2026-03-12 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_transportjob_status_truck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='description',
            field=models.TextField(blank=True, help_text='Describe truck condition, features, etc.', null=True),
        ),
        migrations.CreateModel(
            name='TruckImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='truck_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='logistics.truck')),
            ],
        ),
    ]
