# Generated by Django 6.0.3 on 2026-03-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_truck_description_truckimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mombasa to Nairobi', max_length=255)),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('polyline', models.TextField(help_text='Encoded string representing the road path')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estimated_time', models.DurationField()),
            ],
        ),
    ]
