# Generated by Django 6.0.3 on 2026-03-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_location_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verified',
            new_name='is_verified_seller',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verification_note',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'Regular User'), ('FISHERMAN', 'Fisherman'), ('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('DRIVER', 'Driver'), ('STORAGE', 'Storage'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
