# Generated by Django 6.0.3 on 2026-03-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='supplies_images/'),
        ),
    ]
